numbers = [1, 2, 3, 4]
print(numbers)
numbers.append(10)
print(numbers)
numbers.insert(1,999)
print(numbers)
numbers.append(10)
print(numbers)
numbers.remove(10)
print(numbers)
numbers.pop()
print(numbers)